server:
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology
        version: 5.4.0
        url: classpath:/hl7.terminology#5.4.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      ch-emed:
        name: ch.fhir.ig.ch-emed
        version: 5.0.0-ballot 
      ch-ips:
        name: ch.fhir.ig.ch-ips
        version: 1.0.0-ballot 
      ch-vacd:
        name: ch.fhir.ig.ch-vacd
        version: 5.0.0-ballot 
      ch-allergyintolerance:
        name: ch.fhir.ig.ch-allergyintolerance
        version: 3.0.0-ballot 
      ch-lab-report:
        name: ch.fhir.ig.ch-lab-report
        version: 1.0.0-ballot
      ch-lab-order:
        name: ch.fhir.ig.ch-lab-order
        version: 2.0.0
      ch-rad-order:
        name: ch.fhir.ig.ch-rad-order
        version: 2.0.0-ballot
      ch-etoc:
        name: ch.fhir.ig.ch-etoc
        version: 3.0.0-ballot
      ch-epr-fhir:
        name: ch.fhir.ig.ch-epr-fhir
        version: 4.0.1-ballot 
      ch-atc:
        name: ch.fhir.ig.ch-atc
        version: 3.3.0-ballot
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      suppressWarnInfo:
        hl7.fhir.r4.core#4.0.1:
          - "Constraint failed: dom-6:"