server:
  servlet:
    context-path: /matchbox
hapi:
  fhir:
    server_address: http://localhost:8080/matchbox/fhir
    implementationguides:
      fhir_r5_core:
        name: hl7.fhir.r5.core
        version: 5.0.0
        url: classpath:/hl7.fhir.r5.core.tgz
      fhir_terminology:
        name: hl7.terminology.r5
        version: 6.2.0
        url: classpath:/hl7.terminology.r5#6.2.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions#1.0.0.tgz
      cda:
        name: hl7.cda.uv.core
        version: 2.0.0-sd-202406-matchbox-patch
        url: classpath:/hl7.cda.uv.core#2.0.0-sd-202406-matchbox-patch.tgz
    staticLocation: file:/apps/
    fhir_version: R5
matchbox:
  fhir:
    context:
      txServer: http://tx.fhir.org
      onlyOneEngine: true
