server:
  servlet:
    context-path: /matchbox
spring:
  datasource:
    url: 'jdbc:postgresql://matchbox-db:5432/matchbox'
    username: matchbox
    password: matchbox
    driverClassName: org.postgresql.Driver

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
hapi:
  fhir:
    implementationguides:
      cda:
        url: https://github.com/ahdis/cda-core-2.0/releases/download/v0.0.3-dev/package.tgz
        name: hl7.fhir.cda
        version: 2.1.0
      cdach:
        name: ch.fhir.ig.cda-fhir-maps
        version: 0.3.0
      iheformatcodefhir:
        name: ihe.formatcode.fhir
        version: 1.0.0
      eprterm:
        name: ch.fhir.ig.ch-epr-term
        version: 2.0.7
      core:
        name: ch.fhir.ig.ch-core
        version: 2.0.0
      emed:
        name: ch.fhir.ig.ch-emed
        version: 2.0.0
      vacd:
        name: ch.fhir.ig.ch-vacd
        version: 2.0.0
      atc:
        name: ch.fhir.ig.ch-atc
        version: 3.1.0
      sdc:
        name: hl7.fhir.uv.sdc
        version: 2.7.0
      chorf:
        name: ch.fhir.ig.ch-orf
        version: 1.0.0
      chradorder:
        name: ch.fhir.ig.ch-rad-order
        version: 1.0.0
      hl7fhiruvips:
        name: hl7.fhir.uv.ips
        version": 1.0.0
      chetoc:
        name: ch.fhir.ig.ch-etoc
        version: 1.0.0
      mhd:
        name: ihe.mhd.fhir
        version: 4.0.1
      pixm:
        name: IHE.ITI.PIXm
        version: 3.0.0
      cheprmhealth:
        name: ch.fhir.ig.ch-epr-mhealth
        version: 1.0.0
      challergyintolerance:
        name: ch.fhir.ig.ch-allergyintolerance
        version": 1.0.0