server:
  port: 8080
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology.r4
        version: 6.1.0
        url: classpath:/hl7.terminology.r4#6.1.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      ch_elm:
        name: ch.fhir.ig.ch-elm
        version: 1.8.0-cibuild
        url: https://build.fhir.org/ig/ahdis/ch-elm/package.tgz
    staticLocation: file:/apps/
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
#      txServer: http://tx.fhir.org
      txServer: http://localhost:${server.port}/matchboxv3/fhir
      txUseEcosystem: false
      txLog: test.html
      txServerCache: false
      suppressWarnInfo:
        hl7.fhir.r4.core#4.0.1:
          - "Constraint failed: dom-6:"
          - "regex:Entry '(.+)' isn't reachable by traversing forwards from the Composition"
        ch.fhir.ig.ch-elm:
          - "regex:Binding for path (.+) has no source, so can't be checked"
          - "regex:None of the codings provided are in the value set 'Observation Interpretation Codes'(.*)"
          - "regex:This element does not match any known slice defined in the profile http://hl7.eu/fhir/laboratory/StructureDefinition/Patient-eu-lab(.+)"    
          - "regex:This element does not match any known slice defined in the profile http://hl7.eu/fhir/laboratory/StructureDefinition/HumanName-eu(.+)"
          - "regex:Does not match slice '(.+)' (.+)"
          - "regex:(.+)Unable to find a match for profile(.+)"
          - "regex:(.+): Specified profile type was '(.+)' in profile '(.+)', but found type '(.+)"
spring:
  datasource:
    url: "jdbc:h2:mem:test"

