server:
  port: 8080
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology
        version: 5.4.0
        url: classpath:/hl7.terminology#5.4.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      ch_elm:
        name: ch.fhir.ig.ch-elm
        version: 1.3.1
        url: https://build.fhir.org/ig/ahdis/ch-elm/package.tgz
    staticLocation: file:/apps/
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://localhost:${server.port}/matchboxv3/fhir
      suppressWarnInfo:
        hl7.fhir.r4.core#4.0.1:
          - "Constraint failed: dom-6:"
          - "regex:Entry '(.+)' isn't reachable by traversing forwards from the Composition"
        ch.fhir.ig.ch-elm:
          - "regex:Binding for path (.+) has no source, so can't be checked"
spring:
  datasource:
    url: "jdbc:h2:mem:test"

