name: Build the Angular GUI and commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "matchbox-frontend/**"

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    defaults:
      run:
        working-directory: ./matchbox-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node
          node-version: 16
          cache: "npm"
          cache-dependency-path: matchbox-frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Remove the old GUI
        run: rm -rf ../matchbox-server/src/main/resources/static

      - name: Move the new GUI
        run: mv dist ../matchbox-server/src/main/resources/static

      - name: Commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "server: rebuild the Angular GUI resources"
          file_pattern: "matchbox-server/src/main/resources/static"
