name: Test the Angular GUI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./matchbox-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node
          node-version: 16
          cache: "npm"
          cache-dependency-path: matchbox-frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Test the build
        run: npm run build
