name: Build the Angular GUI and commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "matchbox-frontend/**"

jobs:
  build-angular-and-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    defaults:
      run:
        working-directory: ./matchbox-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          # https://github.com/actions/setup-node
          node-version: 20
          cache: npm
          cache-dependency-path: matchbox-frontend/package-lock.json

      - name: Install dependencies
        # Use dependencies from the lock file, no unattended updates
        run: npm ci

      - name: Build
        run: npm run build-matchbox

      - name: Commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "server: rebuild the Angular GUI resources"
          file_pattern: "matchbox-server/src/main/resources/static"
