name: Test the Angular GUI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-angular:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./matchbox-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          # https://github.com/actions/setup-node
          node-version: 24
          cache: npm
          cache-dependency-path: matchbox-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test the build
        run: npm run build
