name: Publish to Maven Central Repository

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-and-publish-jar:
    name: Publish to Maven Central Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          java-version: "21"
          distribution: "adopt"
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build with Maven
        run: mvn package --batch-mode --no-transfer-progress --file pom.xml --projects :matchbox,:matchbox-engine -DskipTests -P release

      - name: Publish to Apache Maven Central
        run: mvn deploy -P release --file pom.xml --projects :matchbox,:matchbox-engine -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
# The requirements are described in https://central.sonatype.org/publish/requirements/
# The secrets are managed in https://github.com/ahdis/matchbox/settings/secrets/actions
# The GPG key pair shall have been distributed to a public key server.
# The username/password is for the account at https://issues.sonatype.org and must be authorized for this project.
