name: main

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04

    steps:
      - id: docker_meta
        name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        # compute tags:
        # - always tag with a short commit SHA : (arkhn/image:sha-${GITHUB_SHA::7})
        # - always tag with the branch same (replacing '/' with '-')
        # - when a tag follows semver (eg: v1.2.3), tag with 'latest' and '1.2.3'
        with:
          images: arkhn/hapi-fhir-jpa
          tag-sha: true
          tag-semver: |
            {{version}}
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION_NAME=${{ steps.docker_meta.outputs.version }}
            VERSION_SHA=${GITHUB_SHA::8}
          platforms: linux/amd64
          # always push images to the hub
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}