name: Publish documentation
on:
  workflow_dispatch: # On manual trigger
  push:
    tags:            # On tag creation
      - "*"

jobs:
  build-docs-and-publish:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install mkdocs
        run: pip install -r requirements.txt

      - name: Build static documentation and deploy
        run: mkdocs gh-deploy --force
        # https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages

      - name: Setup Java
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 20
          distribution: adopt
          cache: maven

      - name: Build Javadoc
        run: mvn --batch-mode --no-transfer-progress javadoc:aggregate -f pom.xml

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        # https://github.com/JamesIves/github-pages-deploy-action#configuration-
        with:
          branch: gh-pages            # The destination branch.
          folder: target/site/apidocs # The source folder.
          target-folder: apidocs      # The destination folder.
