# This workflow will build and test a Java project with Maven
name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 20
          distribution: adopt
          cache: maven

      - name: Run the tests in Maven
        timeout-minutes: 15
        # We need a timeout here
        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
