# This workflow will build the Java project with Maven and peform IntelliJ smoke tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Smoke Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "charts/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "charts/**"

jobs:
  build_and_smoke_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Download and install HTTP client
      run: |
        curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"
        unzip ijhttp.zip
    - name: Start server with jetty
      run: |
        mvn jetty:run & export JPA_PROCESS=$!
        sleep 20
    - name: Execute smoke tests
      run: ./ijhttp/ijhttp ./src/test/smoketest/plain_server.http --env-file ./src/test/smoketest/http-client.env.json --env default
    - name: Stop server
      run: kill $JPA_PROCESS
    
