server:
  servlet:
    context-path: /matchbox
spring:
  datasource:
    url: "jdbc:h2:mem:validate-r4"
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
    hikari:
      maximum-pool-size: 10
  ai:
    mcp:
      server:
        name: matchbox-mcp
        version: 0.0.1
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 5.2.0
        url: classpath:/hl7.fhir.uv.extensions.r4#5.2.0.tgz
      fhir_terminology:
        name: hl7.terminology.r4
        version: 6.3.0
        url: classpath:/hl7.terminology.r4#6.3.0.tgz
matchbox:
  fhir:
    context:
      xVersion: true
      onlyOneEngine: true
      txServer: http://tx.fhir.org
      llm:
        provider: openai
        modelName: gpt-4o-mini
        apiKey: sk-xxx


